---
title: Igor Halfeld
timezone: UTC
collections:
  posts:
    title: Posts
    permalink: /:collection/:name
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@igorlui.me
description: 'Software Engineer focused on Front-end engineering and architecture'
baseurl: ''
url: https://igorluiz.me
github_username: igorhalfeld
markdown: kramdown
links:
- title: 'ğŸ Home'
  url: '/'
- title: 'ğŸ¦„ About me'
  url: "/about-me/"
- title: 'ğŸ“ Articles'
  url: "/articles/"
- title: 'ğŸ’» Projects'
  url: "/projects/"
#- title: 'ğŸ§  Training'
#  url: "/training/"
- title: 'ğŸ¥ Videos'
  url: "/videos/"
- title: 'ğŸ—£ Talks'
  url: "/talks/"
- title: 'ğŸ’ƒğŸ¼ Resume'
  url: https://github.com/Halfeld/halfeld.github.io/blob/master/resume.md
sass:
  style: compressed
exclude:
- package.json
- src
- node_modules
