---
title: Igor Halfeld
timezone: UTC
collections:
  posts:
    title: Posts
    permalink: /:collection/:name
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@igorlui.me
description: 'Software Engineer focused on Front-end engineering and architecture'
baseurl: ''
url: https://igorluiz.me
github_username: igorhalfeld
markdown: kramdown

links:
- title: 'Home'
  url: '/'
# - title: 'About me'
#  url: "/about-me/"
- title: 'Articles'
  url: "/articles/"
- title: 'Projects'
  url: "/projects/"
#- title: 'Training'
#  url: "/training/"
- title: 'Videos'
  url: "/videos/"
- title: 'Talks'
  url: "/talks/"

sass:
  style: compressed
exclude:
- package.json
- src
- node_modules
