
title: Igor LuÃ­z
email: igor@devstacks.com.br
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://halfeld.github.io" # the base hostname & protocol for your site
github_username:  halfeld

# Build settings
markdown: kramdown

links:
  - title: About
    url: /
  - title: Articles
    url: /articles/
  - title: Projects
    url: /projects/
  - title: Videos
    url: /videos/
  - title: Talks
    url: /talks/
  - title: Resume
    url: https://github.com/Halfeld/halfeld.github.io/blob/master/resume.md

sass:
  style: compressed

exclude: ['package.json', 'src', 'node_modules']
