---
title: Igor Halfeld
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: igor@devstacks.com.br
description: 'Software Consultant'
baseurl: ''
url: http://igorhalfeld.github.io
github_username: igorhalfeld
markdown: kramdown
links:
- title: About
  url: "/"
- title: Articles
  url: "/articles/"
- title: Projects
  url: "/projects/"
- title: Videos
  url: "/videos/"
- title: Talks
  url: "/talks/"
- title: Resume
  url: https://github.com/Halfeld/halfeld.github.io/blob/master/resume.md
sass:
  style: compressed
exclude:
- package.json
- src
- node_modules
