# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Igor Luíz - Desenvolvedor Front-end
name: "Igor Luíz"
email: igorelmerico@hotmail.com
description: "Desenvolvedor Front-end"

# Build settings
markdown: kramdown
highlighter: rouge



exclude: ['package.json', 'src', 'node_modules']
